//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use crate::{service::Service, tag::Tag};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "address")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chain: i32,
    pub hash: Vec<u8>,
    pub title: Option<String>,
    pub services: Vec<i32>, // TODO: Replace for Service
    pub tags: Vec<i32>,     // TODO: Replace for Tag
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chain::Entity",
        from = "Column::Chain",
        to = "super::chain::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chain,
}

impl Related<super::chain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chain.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
